# Generated by Django 3.0.6 on 2020-05-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'verbose_name': 'State List'},
        ),
    ]
